version: 2.1

# Define the jobs we want to run for this project
jobs:
  deploy:
    docker:
      - image: node:14.15.3
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:        
          name: Installing vue-cli
          command: |
            npm install -g @vue/cli
      - run:        
          name: Installing project dependencies
          command: |
            npm install
      - run:        
          name: Authenticating github
          command: |
            git config user.email "franciscommcastro@gmail.com"
            git config user.name "chicomcastro"
      - add_ssh_keys:
          fingerprints:
            - "e2:59:e9:fb:e1:ed:4e:fd:5a:44:8a:4e:7e:57:20:73"
      - run:        
          name: Build on gh branch
          command: |
            git checkout --orphan gh-pages
            npm run build
      - run:        
          name: Linting
          command: |
            npm run lint
      - run:        
          name: Push to gh branch
          command: |
            git --work-tree dist add --all
            git --work-tree dist commit -m "[ci skip] gh-pages"
            git push origin HEAD:gh-pages --force

# Orchestrate our job run sequence
workflows:
  build_and_deploy:
    jobs:
      - deploy